SYSTEM:
  SEED_VALUE: 42
  USE_EXTRA_DATASET: False

IO:
  NEG_TWEET_FILE_PATH: '../../data/train_neg_full.txt'
  POS_TWEET_FILE_PATH: '../../data/train_pos_full.txt'
  TEST_TWEET_FILE_PATH: '../../data/test_data.txt'
  PP_NEG_TWEET_FILE_PATH: '../../data/preprocessed/train_neg_full.txt'
  PP_POS_TWEET_FILE_PATH: '../../data/preprocessed/train_neg_full.txt'
  PP_TEST_TWEET_FILE_PATH: '../../data/preprocessed/train_neg_full.txt'
  EXTRA_DATA_FILE_PATH: '../../data/additional/training.1600000.processed.noemoticon.csv'

PP:
  DROP_DUPLICATES: True
  AMBIGUOUS_DROP_FACTOR: 0.8     # Only relevant if DROP_DUPLICATES = True
  DROP_NEAR_DUPLICATES: False
  USE_EKPHRASIS: True
  USE_WORD_LVL: True

EKPHRASIS:
  # ['email', 'percent', 'money', 'phone', 'user', 'time', 'url', 'date', 'hashtag'] are the valid options here
  OMIT: []
  # ['email', 'percent', 'money', 'phone', 'user', 'time', 'url', 'date', 'hashtag'] are the valid options here
  NORMALIZE: ['email', 'percent', 'money', 'phone', 'user', 'time', 'url', 'date']
  UNPACK_CONTRACTIONS: True
  UNPACK_HASHTAGS: True
  # ['hashtag', 'allcaps', 'elongated', 'repeated'] are the valid options here
  ANNOTATE: ['elongated']
  SEGMENTOR: "twitter"    # [english, twitter] are the valid options here
  CORRECTOR: "twitter"    # [english, twitter] are the valid options here
  ALL_CAPS_TAG: "single"    # [single, wrap, every] are the valid options here
                            #  Note: applicable only when `allcaps` is included in annotate[]
                            #          - single: add a tag after the last capitalized word
                            #          - wrap: wrap all words with opening and closing tags
                            #          - every: add a tag after each word
  SPELL_CORRECT_ELONGATED: False
  SPELL_CORRECTION: True
  FIX_TEXT: False
  FIX_HTML: False
  REMOVE_TAGS: False
  # ['emoticons', 'slang_dict'] are the valid options here
  DICTIONARIES: ['emoticons']
  TOKENIZER: 'Whitespace'

WORD_LVL:
  LOWER_CASE: False
  REMOVE_USER: True
  CHANGE_USER: False
  USER_REPRESENTATION: '@USER'
  REMOVE_URL: True
  CHANGE_URL: False
  URL_REPRESENTATION: 'HTTPURL'
  REMOVE_ELONGATED: True
  REMOVE_STOPWORDS: True
  REMOVE_PUNCTUATIONS: True
  REMOVE_RETWEETS: True
  NORMALIZE_LAUGHTER: True
  REMOVE_SINGLE_CHARACTERS: True
  REMOVE_ANGLE_BRACKETS: True
  LEMMATIZE: True
  SPELL_CORRECTION: False
  NORMALIZE_REPEATING_CHARACTERS: False
  REMOVE_NUMERIC: True
  SEGMENT_HASHTAGS: False
  RECONSTRUCT_SMILEYS: False
  REMOVE_EXTRA_SPACES: True
  REMOVE_TRAILING_URL: True
  MANUAL_SPELL_CORRECTION: True
  CLARIFY_EMPTY: True
